"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Message(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class InnerMessage(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        FIELD_FIELD_NUMBER: builtins.int
        field: typing.Text = ...

        def __init__(self,
            *,
            field : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"field",b"field"]) -> None: ...

    NONE_FIELD_NUMBER: builtins.int
    INNER_FIELD_NUMBER: builtins.int

    @property
    def none(self) -> global___Message.None: ...

    @property
    def inner(self) -> global___Message.InnerMessage: ...

    def __init__(self,
        *,
        none : typing.Optional[global___Message.None] = ...,
        inner : typing.Optional[global___Message.InnerMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"inner",b"inner",u"none",b"none"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"inner",b"inner",u"none",b"none"]) -> None: ...
global___Message = Message
