"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Enum(metaclass=_Enum):
    V = typing.NewType('V', builtins.int)

global___Enum = Enum

Other = Enum.V(1)

class _Enum(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Enum.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    Other = Enum.V(1)

class Message(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ENUM_FIELD_NUMBER: builtins.int
    enum: global___Enum.V = ...

    def __init__(self,
        *,
        enum : global___Enum.V = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"enum",b"enum"]) -> None: ...
global___Message = Message
